const sounds = require("./sounds");
const actions = require("./actions");

let keywords = {
    "aire": [actions.wind, sounds.wind, actions.turn_off_switch],
    "viento": [actions.wind, sounds.wind, actions.turn_off_switch],
    "bosque": [actions.forest, sounds.birds],
    "aves": [sounds.birds],
    "ave": [sounds.birds],
    "pajaro": [sounds.birds],
    "pajaros": [sounds.birds],
    "día": [actions.day, sounds.birds],
    "noche": [actions.dark, sounds.wind],
    "oceano": [actions.ocean, sounds.ocean],
    "mar": [actions.ocean_day, sounds.ocean],
    "mares": [actions.ocean_night, sounds.ocean],
    "playa": [actions.beach, sounds.ocean],
    "campamento": [actions.fire, sounds.fireplace],
    "acampar": [actions.fire, sounds.fireplace],
    "fogata": [actions.fire, sounds.fireplace],
    "correr": [actions.wind, sounds.run, actions.turn_off_switch],
    "corriendo": [actions.wind, sounds.run, actions.turn_off_switch],
    "corrió": [actions.wind, sounds.run, actions.turn_off_switch],
    "rió": [sounds.laugh],
    "feliz": [sounds.laugh],
    "risas": [sounds.laugh],
    "lluvia": [actions.rain, actions.wind, sounds.rain, actions.turn_off_switch],
    "tormenta": [actions.rain, actions.wind, sounds.rain, actions.turn_off_switch],
    "llueve": [actions.rain, actions.wind, sounds.rain, actions.turn_off_switch],
    "perro": [sounds.dog],
    "perros": [sounds.dog],
    "gato": [sounds.cat],
    "gatos": [sounds.cat],
    "puerta": [sounds.wood],
    "castillo": [sounds.wood],
    "cabaña": [sounds.wood],
    "rayo": [actions.white_thunder_on, sounds.light, actions.white_thunder_off, actions.white_thunder_on],
    "trueno": [actions.yellow_thunder_on, sounds.light, actions.yellow_thunder_off, actions.yellow_thunder_on],
    "relampago": [actions.white_thunder_on, sounds.light, actions.white_thunder_off, actions.white_thunder_on],
    "cocinar": [sounds.cooking],
    "cocinando": [sounds.cooking],
    "fantasma": [actions.dark, sounds.chorus],
    "fantasmas": [actions.dark, sounds.chorus],
    "coro": [sounds.chorus],
    "agua": [actions.ocean_day, sounds.water],
    "moneda": [actions.gold, sounds.coins, actions.turn_on_light],
    "dinero": [actions.gold, sounds.coins, actions.turn_on_light],
    "monedas": [actions.gold, sounds.coins, actions.turn_on_light],
    "riquezas": [actions.gold, sounds.coins, actions.turn_on_light],
}

module.exports = keywords;